### ISSUE TITLE
Crashes and unviewable

### ISSUE THREAD

**Issue by frakman1** [JW97/LIFXEffects#1]
Hi there. 
Thank you for writing this tweak and making it available. 
By the way, what version of LIFX app is it supposed to run on? What iOS is it for?
I just tried it on my iOS 7.1.1 iPhone5 on the LIFX App version 1.8.2 and two things are apparent:

1- When I tap on 'Effects', I can't fully see the new addition under 'Color Cycle'. I can barely make out the top bit of the switch.  See screenshot here: http://imgur.com/NqFde0w

2- After several tries,I managed to select that top switch. The Effects icon started blinking blue and then the app crashed. See CrashReporter log here: http://pastebin.com/Ajb0jHVs

**Comment by JW97** [comment]
I haven't touched this tweak in a long time and its unlikely that it works with the current version of the app.

I made it when the app was in its infancy and had very limited effects

**Comment by frakman1** [comment]
I understand. I don't expect it to be updated. I was just curious what version of the LIFX App it worked with that's all. That way, I can find it and install it on my iPhone and get it to work that way.

**Comment by JW97** [comment]
Honestly, I've no idea. Sorry I can't be of any more help but its been over a year since i even remembered this project existed

**Comment by frakman1** [comment]
No worries. I shall continue to follow your work with interest. I learned a lot from your github code. Thank you again for making it freely available.
